### ISSUE TITLE
Escrever o Plano de Testes

### ISSUE THREAD

**Issue by ghost** [ESEGroup/Equador#8]
Plano de Testes, que pode ser encontrado em: 
Wiki/Diagramas > abre o link. Artefatos/Planejamento de Testes/Plano de Testes v1.0.0.docx

**Comment by joaoceles** [comment]
Plano de testes atualizado já na pasta: 

Wiki/Diagramas > abre o link. Artefatos/Planejamento de Testes/Plano de Testes v1.1.0.docx
